# -*- coding: utf-8 -*-
"""Wellhead_Choke_ML_PROJECT_FINAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dK5nG4o4hRS7yqYIswmWx23O7C6Cald5

# Prediction of Two-Phase Flow Rate Through Wellhead Chokes

This notebook develops a machine-learning approach for predicting gross liquid rate (Ql) through wellhead chokes in oil wells.

The objective is to estimate liquid production from wellhead and choke measurements. The analysis follows the project methodology from data preparation and exploratory analysis through feature engineering, empirical correlation, regression-model comparison, model selection, hyperparameter tuning, diagnostics, and field-level analysis.

A fixed random seed of 42 is used throughout the analysis.

# Project methodology

The analysis follows this sequence:

1. Data loading and audit
2. Exploratory data analysis
3. Data cleaning and 3σ outlier filtering
4. Feature engineering
5. Data splitting and scaling
6. Gilbert baseline
7. Comparison of ten regression models
8. Comparison of alternative feature sets
9. Cross-validation and selection of the top three models
10. Extra Trees hyperparameter tuning
11. Model diagnostics
12. Field-level analysis

The original CS229 dataset is used when `RawData.xlsx` with the expected `All_OL` structure is available. Otherwise, the public Sorush wellhead-choke dataset is used as a separate experimental dataset.

# Methodological scope

The implementation follows the project specification and evaluates the effect of pressure-related features, different regression models, and model-selection procedures. Results are reported for the dataset actually loaded by the notebook.
"""

# 1. SETUP
import sys, os, re, math, json, warnings, subprocess, importlib, urllib.request
from pathlib import Path

packages = {
    "numpy":"numpy", "pandas":"pandas", "matplotlib":"matplotlib",
    "seaborn":"seaborn", "sklearn":"scikit-learn",
    "openpyxl":"openpyxl", "requests":"requests", "joblib":"joblib"
}
for module, package in packages.items():
    try:
        importlib.import_module(module)
    except ImportError:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", package])

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import requests

from sklearn.model_selection import train_test_split, KFold, cross_val_score, RandomizedSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.linear_model import LinearRegression, Ridge, BayesianRidge
from sklearn.neural_network import MLPRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, ExtraTreesRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

warnings.filterwarnings("ignore")
SEED = 42
np.random.seed(SEED)

ROOT = Path.cwd() / "wellhead_choke_phase1_12_project"
for name in ["data","figures","results","models","src","report"]:
    (ROOT/name).mkdir(parents=True, exist_ok=True)

print("Project directory:", ROOT)
print("Python:", sys.version.split()[0])
print("Seed:", SEED)

"""# 2. Data loading

The notebook first searches for the original `RawData.xlsx` dataset and verifies the expected `All_OL` structure.

If the original dataset is not available, the public Sorush wellhead-choke dataset is loaded. The workbook is inspected to identify the worksheet and header containing the required measurement table.
"""

# 2. ROBUST DATA LOADER
def norm(x):
    return re.sub(r"[^a-z0-9]+", "", str(x).strip().lower())

def clean_columns(df):
    df = df.copy()
    # Drop columns that are completely empty
    df = df.dropna(axis=1, how="all")
    # Remove Excel-generated blank columns
    keep = [c for c in df.columns if not str(c).strip().lower().startswith("unnamed")]
    df = df.loc[:, keep]
    # Drop completely blank rows
    df = df.dropna(axis=0, how="all")
    return df.reset_index(drop=True)

def find_header_row(raw_sheet, required_aliases, max_rows=50):
    scan = raw_sheet.iloc[:max_rows].copy()
    best_row, best_score, best_hits = None, -1, {}
    for r in range(len(scan)):
        vals = [norm(v) for v in scan.iloc[r].tolist()]
        hits = {}
        for canonical, aliases in required_aliases.items():
            aliases_n = [norm(a) for a in aliases]
            hit = None
            for j, v in enumerate(vals):
                if v in aliases_n:
                    hit = j
                    break
            hits[canonical] = hit
        score = sum(v is not None for v in hits.values())
        if score > best_score:
            best_row, best_score, best_hits = r, score, hits
    return best_row, best_score, best_hits

def load_sheet_with_detected_header(path, sheet_name, required_aliases):
    raw_sheet = pd.read_excel(path, sheet_name=sheet_name, header=None)
    header_row, score, hits = find_header_row(raw_sheet, required_aliases)
    if header_row is None or score < len(required_aliases):
        return None, {"header_row":header_row, "score":score, "hits":hits}
    df = pd.read_excel(path, sheet_name=sheet_name, header=header_row)
    df = clean_columns(df)
    return df, {"header_row":header_row, "score":score, "hits":hits}

def audit_workbook(path, required_aliases, preferred_sheet=None):
    xl = pd.ExcelFile(path)
    rows=[]
    best=None
    for sh in xl.sheet_names:
        raw_sheet=pd.read_excel(path,sheet_name=sh,header=None,nrows=50)
        hr,score,hits=find_header_row(raw_sheet,required_aliases)
        rows.append({
            "sheet":sh,"detected_header_row":hr,"required_fields_found":score,
            "required_fields_total":len(required_aliases)
        })
        if score==len(required_aliases):
            preference = 1 if preferred_sheet and sh.strip().lower()==preferred_sheet.strip().lower() else 0
            candidate=(preference, score, sh)
            if best is None or candidate>best[0]:
                best=(candidate,sh,hr,hits)
    return xl.sheet_names,pd.DataFrame(rows),best

ORIGINAL_ALIASES = {
    "Group":["Group"], "Gross":["Gross"], "Oil":["Oil"], "Water":["Water"],
    "waterCut":["waterCut","water cut"], "GOR":["GOR"], "GLR":["GLR"],
    "FWHP":["FWHP"], "Press":["Press"], "Temp":["Temp"],
    "chokeSize":["chokeSize","choke size"], "CHK_US":["CHK_US"], "CHK_DS":["CHK_DS"]
}
REPLACEMENT_ALIASES = {
    "D64":["D64","D(1/64) in","D(1/64)in","choke size","chokesize"],
    "Pwh":["Pwh","P(psi)","Pwh(psi)","PWH"],
    "GLR":["GLR","GLR(SCF/D)","GLR(SCF/D)"],
    "QL":["QL","Qliq","Qliq,exp(STB/D)","Qliq exp (STB/D)","liquid rate"]
}

original_candidates=[
    Path("RawData.xlsx"), Path("/mnt/data/RawData.xlsx"),
    ROOT/"data"/"RawData.xlsx"
]
orig=None
for p in original_candidates:
    if p.exists():
        try:
            sheets,aud,best=audit_workbook(p,ORIGINAL_ALIASES)
            if best is not None:
                df0,info=load_sheet_with_detected_header(p,best[1],ORIGINAL_ALIASES)
                if df0 is not None:
                    orig=(p,best[1],df0,info,aud)
                    break
        except Exception:
            pass

if orig is not None:
    orig_path,orig_sheet,raw,load_info,workbook_audit=orig
    DATA_MODE="ORIGINAL_CS229"
    print("✓ ORIGINAL CS229 DATA FOUND")
    print("File:",orig_path)
    print("Sheet:",orig_sheet)
    print("Shape:",raw.shape)
else:
    DATA_MODE="PUBLIC_REPLACEMENT"
    print("Original RawData.xlsx was not found.")
    print("Using the documented public Sorush replacement dataset.")

    url="https://media.springernature.com/original/springer-static/esm/art%3A10.1007%2Fs13202-021-01087-4/MediaObjects/13202_2021_1087_MOESM1_ESM.xlsx"
    dest=ROOT/"data"/"Sorush_7245_public.xlsx"
    if not dest.exists():
        try:
            r=requests.get(url,timeout=90)
            r.raise_for_status()
            dest.write_bytes(r.content)
        except Exception as e:
            try:
                urllib.request.urlretrieve(url,str(dest))
            except Exception:
                raise RuntimeError(
                    "Could not download the public replacement workbook. "
                    "Download the Springer supplementary Excel workbook and place it at "
                    f"{dest}, then rerun this cell. Original error: {e}"
                )

    sheets,workbook_audit,best=audit_workbook(
        dest,REPLACEMENT_ALIASES,preferred_sheet="7245-Sample Dataset"
    )
    workbook_audit.to_csv(ROOT/"results"/"workbook_sheet_audit.csv",index=False)
    display(workbook_audit)

    if best is None:
        raise RuntimeError(
            "No worksheet contains all required replacement variables "
            "(D64, Pwh, GLR, QL). Inspect workbook_sheet_audit.csv."
        )

    _,chosen_sheet,chosen_header,_=best
    raw,load_info=load_sheet_with_detected_header(
        dest,chosen_sheet,REPLACEMENT_ALIASES
    )
    if raw is None:
        raise RuntimeError("Detected a candidate sheet but could not reload its header correctly.")

    print("✓ Replacement dataset loaded")
    print("Sheet:",chosen_sheet)
    print("Detected header row:",chosen_header)
    print("Raw shape:",raw.shape)

print("DATA_MODE:",DATA_MODE)
print("Columns before canonicalization:",list(raw.columns))

# 2B. CANONICALIZE AND VALIDATE THE LOADED TABLE
def canonicalize_replacement(df):
    mapping={}
    for c in df.columns:
        n=norm(c)
        if n in {norm(x) for x in REPLACEMENT_ALIASES["D64"]}: mapping[c]="D64"
        elif n in {norm(x) for x in REPLACEMENT_ALIASES["Pwh"]}: mapping[c]="Pwh"
        elif n in {norm(x) for x in REPLACEMENT_ALIASES["GLR"]}: mapping[c]="GLR"
        elif n in {norm(x) for x in REPLACEMENT_ALIASES["QL"]}: mapping[c]="QL"
    out=df.rename(columns=mapping).copy()
    out=clean_columns(out)
    # If duplicate canonical names somehow exist, keep the first non-empty one.
    out=out.loc[:,~out.columns.duplicated()]
    return out

if DATA_MODE=="PUBLIC_REPLACEMENT":
    raw=canonicalize_replacement(raw)
    required=["D64","Pwh","GLR","QL"]
    missing=[c for c in required if c not in raw.columns]
    if missing:
        raise RuntimeError(
            f"Replacement dataset validation failed. Missing {missing}. "
            f"Detected columns: {list(raw.columns)}"
        )
    for c in required:
        raw[c]=pd.to_numeric(raw[c],errors="coerce")
    raw=raw.dropna(subset=required).copy()
    print("✓ REQUIRED REPLACEMENT COLUMNS:",required)
    print("✓ Rows after required-column numeric validation:",len(raw))
    print(raw[required].head())
else:
    raw=clean_columns(raw)
    print("✓ Original table cleaned of blank/Unnamed columns.")
    print("Original columns:",list(raw.columns))

"""# 3. Data audit

The dataset is examined for dimensions, data types, missing values, duplicate records, and available field or well identifiers.
"""

# 3. AUDIT
raw.insert(0,"_original_row",np.arange(len(raw)))

audit=pd.DataFrame({
    "dtype":raw.dtypes.astype(str),
    "missing":raw.isna().sum(),
    "missing_pct":(raw.isna().mean()*100).round(3),
    "unique":raw.nunique(dropna=False)
})
print("Shape:",raw.shape)
display(audit)
print("Duplicate rows:",raw.duplicated().sum())

field_candidates=[
    c for c in raw.columns
    if norm(c) in {"group","field","well","wellno","wellnumber","wellid","wellname"}
    or "field" in norm(c) or "well" in norm(c)
]
print("Possible field/well columns:",field_candidates)
for c in field_candidates:
    print(f"{c}: {raw[c].nunique(dropna=True)} unique")
    display(raw[c].value_counts(dropna=False).head(15))

"""# 4. Exploratory data analysis

The numerical variables are summarized and their distributions and pairwise correlations are examined. Feature distributions and the correlation matrix provide an initial view of the relationships between the measured variables and liquid rate.
"""

# 4. EDA
numeric=raw.select_dtypes(include=[np.number]).copy()
numeric=numeric.drop(columns=["_original_row"],errors="ignore")
numeric=numeric.dropna(axis=1,how="all")

print("Numeric columns used in EDA:",list(numeric.columns))
display(numeric.describe().T)

if numeric.shape[1] >= 2:
    plt.figure(figsize=(11,7))
    corr=numeric.corr()
    sns.heatmap(corr,annot=True,fmt=".2f",cmap="coolwarm",center=0,square=False)
    plt.title("Numeric Feature Correlation Heatmap")
    plt.tight_layout()
    plt.savefig(ROOT/"figures"/"correlation_heatmap.png",dpi=180)
    plt.show()
else:
    raise RuntimeError("EDA found fewer than two valid numeric columns. Data loading is incorrect.")

for c in numeric.columns:
    plt.figure(figsize=(7,4))
    sns.histplot(numeric[c].dropna(),kde=True)
    plt.title(f"Distribution: {c}")
    plt.xlabel(c)
    plt.tight_layout()
    plt.savefig(ROOT/"figures"/f"hist_{norm(c)}.png",dpi=150)
    plt.show()

"""# 5. Feature engineering

For the original dataset, the engineered variables follow the project methodology:

- ΔP = FWHP − CHK_DS
- Pdn/Pup = CHK_DS/FWHP
- Flow regime is classified as critical when Pdn/Pup ≤ 0.5
- WC = 100 − waterCut, following the definition used by the reference implementation
- ΔP/Pup
- Gross/FWHP as the pressure-normalized target

For the public replacement dataset, only variables that are actually available in the dataset are used.
"""

# 5. FEATURE ENGINEERING
df=raw.copy()

def resolve_col(df,candidates):
    ns={norm(c):c for c in df.columns}
    for x in candidates:
        if norm(x) in ns:
            return ns[norm(x)]
    return None

if DATA_MODE=="ORIGINAL_CS229":
    C={k:resolve_col(df,v) for k,v in ORIGINAL_ALIASES.items()}
    missing=[k for k,v in C.items() if v is None]
    if missing:
        raise RuntimeError(f"Original schema validation failed; missing: {missing}")

    for c in C.values():
        df[c]=pd.to_numeric(df[c],errors="coerce")

    df["DP"]=df[C["FWHP"]]-df[C["CHK_DS"]]
    df["Pdn_Pup"]=df[C["CHK_DS"]]/df[C["FWHP"]].replace(0,np.nan)
    df["FlowRegime"]=(df["Pdn_Pup"]<=0.5).astype(int)
    df["WC"]=100-df[C["waterCut"]]
    df["DP_over_Pup"]=df["DP"]/df[C["FWHP"]].replace(0,np.nan)
    df["PressureNormalizedTarget"]=df[C["Gross"]]/df[C["FWHP"]].replace(0,np.nan)

    PUP=C["FWHP"]
    TARGET_RAW=C["Gross"]
    TARGET_NORM="PressureNormalizedTarget"

    FEATURES_A=[
        PUP,C["GLR"],C["chokeSize"],C["Temp"],C["GOR"],
        "DP","WC","DP_over_Pup","FlowRegime"
    ]
    FEATURES_B=[
        C["GLR"],C["chokeSize"],C["Temp"],C["GOR"],
        "DP","WC","DP_over_Pup","FlowRegime"
    ]
    FEATURES_C=[
        C["GLR"],C["chokeSize"],C["Temp"],C["GOR"],"WC"
    ]

    print("Original feature engineering complete.")
    print("Model A:",FEATURES_A)
    print("Model B:",FEATURES_B)
    print("Model C:",FEATURES_C)
    print("Raw target:",TARGET_RAW)
    print("Normalized target:",TARGET_NORM)
else:
    C={"D64":"D64","Pwh":"Pwh","GLR":"GLR","QL":"QL"}
    for c in C.values():
        df[c]=pd.to_numeric(df[c],errors="coerce")

    df["PressureNormalizedTarget"]=df["QL"]/df["Pwh"].replace(0,np.nan)
    TARGET_RAW="QL"
    TARGET_NORM="PressureNormalizedTarget"

    FEATURES_A=["Pwh","D64","GLR"]
    FEATURES_B=["D64","GLR"]
    FEATURES_C=["D64","GLR"]

    print("Replacement feature engineering complete.")
    print("Model A:",FEATURES_A)
    print("Model B:",FEATURES_B)
    print("Model C:",FEATURES_C)
    print("Raw target:",TARGET_RAW)
    print("Normalized target:",TARGET_NORM)

"""# 6. Data cleaning and 3σ outlier removal

Records with invalid numerical values are removed. A three-standard-deviation filter is applied to the model features and raw liquid-rate target.

The pressure-normalized target is calculated after this filtering step and retained for the normalized-target analysis. Record counts before and after filtering are saved, together with feature-versus-target plots.
"""

# 6. CLEAN + 3 SIGMA
if DATA_MODE=="ORIGINAL_CS229":
    cleaning_features=list(dict.fromkeys(FEATURES_A))
    group_col=C["Group"]
else:
    cleaning_features=list(dict.fromkeys(FEATURES_A))
    group_col=None

# Keep the raw target and the columns required for the normalized target.
# Also preserve Group and original row position when available.
needed=cleaning_features+[TARGET_RAW]

if TARGET_NORM not in needed:
    if DATA_MODE=="ORIGINAL_CS229":
        needed += [C["FWHP"]]
    else:
        needed += [C["Pwh"]]

if group_col is not None:
    needed += [group_col]

if "_original_row" in df.columns:
    needed += ["_original_row"]

needed=list(dict.fromkeys(needed))

work=df[needed].copy()
before=len(work)

# Numeric conversion only for quantities used by the ML pipeline.
numeric_needed=list(dict.fromkeys(
    cleaning_features+[TARGET_RAW]+
    ([C["FWHP"]] if DATA_MODE=="ORIGINAL_CS229" else [C["Pwh"]])
))

for c in numeric_needed:
    work[c]=pd.to_numeric(work[c],errors="coerce")

work=work.replace([np.inf,-np.inf],np.nan)
work=work.dropna(subset=numeric_needed).copy()
after_valid=len(work)

# 3σ filtering is deliberately applied to the raw ML features + raw target.
# The normalized target is derived AFTER this filter.
threshold_rows=[]
mask=pd.Series(True,index=work.index)

for c in cleaning_features+[TARGET_RAW]:
    mu=work[c].mean()
    sd=work[c].std(ddof=1)
    lo=mu-3*sd
    hi=mu+3*sd

    threshold_rows.append({
        "feature":c,
        "mean":mu,
        "std":sd,
        "lower":lo,
        "upper":hi
    })

    mask &= work[c].between(lo,hi)

clean=work.loc[mask].copy()

# ------------------------------------------------------------
# IMPORTANT FIX:
# Build and PRESERVE the normalized target in clean.
#
# Original dataset:
#     normalized target = Gross / FWHP
#
# Public replacement:
#     normalized target = QL / Pwh
# ------------------------------------------------------------
if DATA_MODE=="ORIGINAL_CS229":
    clean[TARGET_NORM]=(
        clean[C["Gross"]] /
        clean[C["FWHP"]].replace(0,np.nan)
    )
else:
    clean[TARGET_NORM]=(
        clean["QL"] /
        clean["Pwh"].replace(0,np.nan)
    )

clean=clean.replace([np.inf,-np.inf],np.nan)
clean=clean.dropna(subset=[TARGET_NORM]).copy()

thresholds=pd.DataFrame(threshold_rows)

thresholds.to_csv(
    ROOT/"results"/"three_sigma_thresholds.csv",
    index=False
)

pd.DataFrame([{
    "raw_rows":before,
    "after_numeric_validation":after_valid,
    "after_3sigma":len(clean),
    "removed_total":before-len(clean),
    "removed_pct":100*(before-len(clean))/before
}]).to_csv(
    ROOT/"results"/"cleaning_counts.csv",
    index=False
)

clean.to_csv(
    ROOT/"results"/"clean_3sigma_dataset.csv",
    index=False
)

print(
    f"Rows: {before} → valid: {after_valid} "
    f"→ 3σ clean: {len(clean)}"
)
print("Normalized target:",TARGET_NORM)
print("Normalized target present:",TARGET_NORM in clean.columns)

if DATA_MODE=="ORIGINAL_CS229":
    print("Group column preserved:",group_col in clean.columns)
print("Original row position preserved:", "_original_row" in clean.columns)

display(thresholds)

# Before/after plots
for c in cleaning_features:
    fig,ax=plt.subplots(1,2,figsize=(12,4))

    ax[0].scatter(
        work[c],
        work[TARGET_RAW],
        s=7,
        alpha=.35
    )
    ax[0].set_title(f"Before 3σ: {c} vs Ql")

    ax[1].scatter(
        clean[c],
        clean[TARGET_RAW],
        s=7,
        alpha=.35
    )
    ax[1].set_title(f"After 3σ: {c} vs Ql")

    for a in ax:
        a.set_xlabel(c)
        a.set_ylabel(str(TARGET_RAW))

    plt.tight_layout()
    plt.savefig(
        ROOT/"figures"/
        f"before_after_3sigma_{norm(c)}.png",
        dpi=160
    )
    plt.show()

# 6B. CLEAN-DATA INVARIANT CHECK
assert TARGET_NORM in clean.columns, (
    f"{TARGET_NORM} is missing from clean."
)

assert TARGET_RAW in clean.columns, (
    f"{TARGET_RAW} is missing from clean."
)

for feature in FEATURES_A + FEATURES_B + FEATURES_C:
    assert feature in clean.columns, (
        f"Required feature missing from clean: {feature}"
    )

if DATA_MODE=="ORIGINAL_CS229":
    assert group_col in clean.columns, (
        "Original Group column was not preserved through cleaning."
    )
    assert "_original_row" in clean.columns, (
        "Original row positions were not preserved."
    )

print("✓ Clean-data invariant passed.")
print("✓ Normalized target:",TARGET_NORM)
print("✓ Clean shape:",clean.shape)

"""# 7. Gilbert correlation

A Gilbert-type empirical correlation is used as the physical baseline for comparison with the machine-learning models. Its predictions are evaluated against measured liquid rate using R², MAE, MSE, RMSE, correlation, and MAPE.
"""

# 7. METRICS + GILBERT
def metric_dict(y_true,y_pred):
    yt=np.asarray(y_true,dtype=float)
    yp=np.asarray(y_pred,dtype=float)
    mse=mean_squared_error(yt,yp)
    valid=yt!=0
    return {
        "R2":r2_score(yt,yp),
        "MAE":mean_absolute_error(yt,yp),
        "MSE":mse,
        "RMSE":math.sqrt(mse),
        "Correlation":np.corrcoef(yt,yp)[0,1] if len(yt)>1 else np.nan,
        "MAPE_pct":np.mean(np.abs((yt[valid]-yp[valid])/yt[valid]))*100 if valid.any() else np.nan
    }

if DATA_MODE=="ORIGINAL_CS229":
    gilbert_pred=(
        0.1*clean[C["FWHP"]]*clean[C["chokeSize"]]**1.89/
        clean[C["GLR"]]**0.546
    )
    gilbert_label="Original-schema Gilbert implementation"
else:
    gilbert_pred=(
        0.1*clean["Pwh"]*clean["D64"]**1.89/
        clean["GLR"]**0.546
    )
    gilbert_label="Public-dataset adapted Gilbert-form baseline"

gilbert_metrics=metric_dict(clean[TARGET_RAW],gilbert_pred)
gilbert_out=pd.DataFrame([gilbert_metrics])
gilbert_out.insert(0,"Baseline",gilbert_label)
display(gilbert_out)
gilbert_out.to_csv(ROOT/"results"/"gilbert_metrics.csv",index=False)

plt.figure(figsize=(6,6))
plt.scatter(clean[TARGET_RAW],gilbert_pred,s=9,alpha=.45)
lo=min(clean[TARGET_RAW].min(),np.nanmin(gilbert_pred))
hi=max(clean[TARGET_RAW].max(),np.nanmax(gilbert_pred))
plt.plot([lo,hi],[lo,hi],"k--")
plt.xlabel("Measured Ql")
plt.ylabel("Gilbert predicted Ql")
plt.title(gilbert_label)
plt.tight_layout()
plt.savefig(ROOT/"figures"/"gilbert_predicted_vs_measured.png",dpi=180)
plt.show()

"""# 8. Regression models

Ten regression models are evaluated:

1. Linear Regression
2. Ridge Regression
3. Bayesian Ridge
4. Polynomial Linear Regression
5. Polynomial Ridge Regression
6. MLP Regression
7. K-Nearest Neighbours
8. Random Forest
9. Gradient Tree Boosting
10. Extra Trees

Scaling is performed within the model pipelines so that the scaler is fitted using training data only.
"""

# 8. MODEL FACTORY
def make_models():
    return {
        "Linear Regression":Pipeline([
            ("scaler",StandardScaler()),
            ("model",LinearRegression())
        ]),
        "Ridge":Pipeline([
            ("scaler",StandardScaler()),
            ("model",Ridge(alpha=1.0))
        ]),
        "Bayesian Ridge":Pipeline([
            ("scaler",StandardScaler()),
            ("model",BayesianRidge())
        ]),
        "Polynomial Linear":Pipeline([
            ("poly",PolynomialFeatures(degree=2,include_bias=False)),
            ("scaler",StandardScaler()),
            ("model",LinearRegression())
        ]),
        "Polynomial Ridge":Pipeline([
            ("poly",PolynomialFeatures(degree=2,include_bias=False)),
            ("scaler",StandardScaler()),
            ("model",Ridge(alpha=1.0))
        ]),
        "MLP Regression":Pipeline([
            ("scaler",StandardScaler()),
            ("model",MLPRegressor(
                hidden_layer_sizes=(64,32),
                activation="relu",
                early_stopping=True,
                max_iter=1000,
                random_state=SEED
            ))
        ]),
        "KNN":Pipeline([
            ("scaler",StandardScaler()),
            ("model",KNeighborsRegressor(n_neighbors=7,weights="distance"))
        ]),
        "Random Forest":RandomForestRegressor(
            n_estimators=300,random_state=SEED,n_jobs=-1
        ),
        "Gradient Tree Boosting":GradientBoostingRegressor(
            n_estimators=300,random_state=SEED
        ),
        "Extra Trees":ExtraTreesRegressor(
            n_estimators=300,random_state=SEED,n_jobs=-1
        )
    }

MODEL_NAMES=list(make_models())
print(MODEL_NAMES)

"""# 9. Data splitting

The initial model comparison uses an 80/20 train/test split. The later model-selection experiment uses an 80/10/10 train/test/validation split.

When field labels are available, the splits preserve the field distribution.
"""

# 9. SPLIT HELPERS
def get_group_series(frame):
    if DATA_MODE=="ORIGINAL_CS229":
        if group_col in frame.columns:
            return frame[group_col]
    return None


def split_80_20(X,y,groups=None):
    """
    Returns the actual index labels used for train/test.
    Keeping the indices lets us back-transform normalized predictions
    using exactly the same held-out rows.
    """
    if groups is not None and groups.nunique(dropna=True)>=2:
        train_idx,test_idx=train_test_split(
            X.index,
            test_size=.2,
            random_state=SEED,
            stratify=groups
        )
    else:
        train_idx,test_idx=train_test_split(
            X.index,
            test_size=.2,
            random_state=SEED
        )

    return (
        X.loc[train_idx],
        X.loc[test_idx],
        y.loc[train_idx],
        y.loc[test_idx],
        train_idx,
        test_idx
    )


def split_80_10_10(X,y,groups=None):
    if groups is not None and groups.nunique(dropna=True)>=2:
        Xtr,Xhold,ytr,yhold,gtr,ghold=train_test_split(
            X,y,groups,
            test_size=.2,
            random_state=SEED,
            stratify=groups
        )
        Xte,Xva,yte,yva=train_test_split(
            Xhold,yhold,
            test_size=.5,
            random_state=SEED,
            stratify=ghold
        )
    else:
        Xtr,Xhold,ytr,yhold=train_test_split(
            X,y,
            test_size=.2,
            random_state=SEED
        )
        Xte,Xva,yte,yva=train_test_split(
            Xhold,yhold,
            test_size=.5,
            random_state=SEED
        )

    return Xtr,Xte,Xva,ytr,yte,yva

"""# 10. Initial 80/20 model comparison

The ten regression models are trained using the initial feature set and evaluated on held-out test data. Predicted-versus-measured plots are generated for visual comparison.
"""

Í# 10. INITIAL 80/20 SCREEN
def run_screen(frame,features,target):
    X=frame[features].copy()
    y=frame[target].copy()

    groups=get_group_series(frame)

    Xtr,Xte,ytr,yte,train_idx,test_idx=split_80_20(
        X,y,groups
    )

    rows=[]
    predictions={}
    fitted={}

    for name,model in make_models().items():
        model.fit(Xtr,ytr)

        pred=model.predict(Xte)

        m=metric_dict(yte,pred)
        m.update({
            "Model":name,
            "Target":target,
            "Train_n":len(Xtr),
            "Test_n":len(Xte)
        })

        rows.append(m)
        predictions[name]=(yte,pred)
        fitted[name]=model

    result=pd.DataFrame(rows).sort_values(
        "R2",
        ascending=False
    ).reset_index(drop=True)

    return (
        result,
        predictions,
        fitted,
        test_idx
    )


screen_results,screen_preds,screen_models,screen_test_idx=run_screen(
    clean,
    FEATURES_A,
    TARGET_RAW
)

display(screen_results)

screen_results.to_csv(
    ROOT/"results"/"initial_80_20_all10.csv",
    index=False
)

for name,(yt,yp) in screen_preds.items():
    plt.figure(figsize=(5.5,5.5))

    plt.scatter(
        yt,
        yp,
        s=9,
        alpha=.45
    )

    lo=min(yt.min(),yp.min())
    hi=max(yt.max(),yp.max())

    plt.plot(
        [lo,hi],
        [lo,hi],
        "k--"
    )

    plt.xlabel("Measured Ql")
    plt.ylabel("Predicted Ql")
    plt.title(f"{name} — 80/20")

    plt.tight_layout()

    plt.savefig(
        ROOT/"figures"/
        f"initial_{norm(name)}.png",
        dpi=150
    )

    plt.show()

"""# 11. Model A, Model B, and Model C

Three feature configurations are compared.

**Model A** uses the raw feature set, including upstream-pressure information.

**Model B** follows the paper-oriented approach by removing direct upstream pressure while retaining the specified derived pressure terms.

**Model C** provides a stricter test in which upstream-pressure-derived variables are removed where the available data allow this distinction.
"""

# 11. MODEL A/B/C COMPARISON
def compare_feature_sets(frame,target):
    all_rows=[]
    details={}

    sets={
        "Model A":FEATURES_A,
        "Model B":FEATURES_B,
        "Model C":FEATURES_C
    }

    for label,features in sets.items():
        res,preds,models,test_idx=run_screen(
            frame,
            features,
            target
        )

        res.insert(
            0,
            "FeatureSet",
            label
        )

        all_rows.append(res)

        details[label]={
            "results":res,
            "predictions":preds,
            "models":models,
            "test_idx":test_idx
        }

    return (
        pd.concat(
            all_rows,
            ignore_index=True
        ),
        details
    )


abc_results,abc_details=compare_feature_sets(
    clean,
    TARGET_RAW
)

display(
    abc_results.sort_values(
        ["FeatureSet","R2"],
        ascending=[True,False]
    )
)

abc_results.to_csv(
    ROOT/"results"/
    "model_A_B_C_raw_target.csv",
    index=False
)

"""# 12. Normalized target

The pressure-normalized target is evaluated separately from the raw liquid-rate target. For the original dataset, the normalized target is Gross/FWHP. Predictions from the Extra Trees model can subsequently be converted back to the original liquid-rate scale using FWHP.
"""

# 12. NORMALIZED TARGET SCREEN

# Defensive check: Step 6 should already have created this column.
if TARGET_NORM not in clean.columns:
    print(
        f"WARNING: {TARGET_NORM} was missing; "
        "rebuilding it defensively."
    )

    if DATA_MODE=="ORIGINAL_CS229":
        clean[TARGET_NORM]=(
            clean[C["Gross"]] /
            clean[C["FWHP"]].replace(0,np.nan)
        )
    else:
        clean[TARGET_NORM]=(
            clean["QL"] /
            clean["Pwh"].replace(0,np.nan)
        )

    clean=clean.replace(
        [np.inf,-np.inf],
        np.nan
    )

    clean=clean.dropna(
        subset=[TARGET_NORM]
    ).copy()

assert TARGET_NORM in clean.columns

print(
    "Running normalized-target screen on:",
    TARGET_NORM
)

norm_results,norm_preds,norm_models,norm_test_idx=run_screen(
    clean,
    FEATURES_B,
    TARGET_NORM
)

display(norm_results)

norm_results.to_csv(
    ROOT/"results"/
    "normalized_target_80_20.csv",
    index=False
)

# ------------------------------------------------------------
# BACK-TRANSFORMATION TO RAW Ql
#
# Original dataset:
#     normalized target = Gross / FWHP
#
# Therefore:
#     predicted Gross = predicted normalized target * FWHP
#
# The exact test indices returned by run_screen() are used.
# No second split is reconstructed.
# ------------------------------------------------------------
if DATA_MODE=="ORIGINAL_CS229":

    model=norm_models["Extra Trees"]

    pred_norm=model.predict(
        clean.loc[
            norm_test_idx,
            FEATURES_B
        ]
    )

    pup_hold=clean.loc[
        norm_test_idx,
        C["FWHP"]
    ].to_numpy()

    q_pred=pred_norm*pup_hold

    q_true=clean.loc[
        norm_test_idx,
        TARGET_RAW
    ].to_numpy()

    back_metrics=metric_dict(
        q_true,
        q_pred
    )

    print(
        "Extra Trees normalized-target "
        "predictions back-transformed to raw Ql:"
    )

    display(
        pd.DataFrame([back_metrics])
    )

    pd.DataFrame(
        [back_metrics]
    ).to_csv(
        ROOT/"results"/
        "normalized_ET_backtransformed_raw_scale.csv",
        index=False
    )

    plt.figure(figsize=(6,6))

    plt.scatter(
        q_true,
        q_pred,
        s=10,
        alpha=.5
    )

    lo=min(
        q_true.min(),
        q_pred.min()
    )
    hi=max(
        q_true.max(),
        q_pred.max()
    )

    plt.plot(
        [lo,hi],
        [lo,hi],
        "k--"
    )

    plt.xlabel("Measured Ql")
    plt.ylabel("Predicted Ql")
    plt.title(
        "Extra Trees — Normalized Target "
        "Back-Transformed to Ql"
    )

    plt.tight_layout()

    plt.savefig(
        ROOT/"figures"/
        "normalized_ET_backtransformed_predicted_vs_actual.png",
        dpi=170
    )

    plt.show()

"""# 13. Top-three model selection

The candidate models are evaluated using five-fold cross-validation on the training data. The three models with the highest mean cross-validated R² are selected for detailed evaluation.
"""

# 13. TOP-3 BY TRAIN-ONLY CV
X=clean[FEATURES_A].copy()
y=clean[TARGET_RAW].copy()
groups=get_group_series(clean)
X_train,X_test,X_val,y_train,y_test,y_val=split_80_10_10(X,y,groups)

cv=KFold(n_splits=5,shuffle=True,random_state=SEED)
cv_rows=[]
for name,model in make_models().items():
    scores=cross_val_score(
        model,X_train,y_train,
        cv=cv,scoring="r2",n_jobs=-1
    )
    cv_rows.append({
        "Model":name,
        "CV_R2_mean":scores.mean(),
        "CV_R2_std":scores.std()
    })

cv_results=pd.DataFrame(cv_rows).sort_values("CV_R2_mean",ascending=False).reset_index(drop=True)
top3=cv_results.head(3)["Model"].tolist()
display(cv_results)
print("TOP 3:",top3)
cv_results.to_csv(ROOT/"results"/"top3_train_only_cv.csv",index=False)

"""# 14. Top-three evaluation

The selected models are evaluated using the 80/10/10 train, test, and validation split. Performance is reported separately for each split using R², MAE, MSE, RMSE, correlation, and MAPE.
"""

# 14. TOP-3 80/10/10
top3_rows=[]
top3_models={}
top3_predictions={}

for name in top3:
    model=make_models()[name]
    model.fit(X_train,y_train)
    top3_models[name]=model

    for split,XX,yy in [
        ("train",X_train,y_train),
        ("test",X_test,y_test),
        ("validation",X_val,y_val)
    ]:
        pred=model.predict(XX)
        m=metric_dict(yy,pred)
        m.update({"Model":name,"Split":split})
        top3_rows.append(m)
        top3_predictions[(name,split)]=(yy,pred)

top3_eval=pd.DataFrame(top3_rows)
display(top3_eval)
top3_eval.to_csv(ROOT/"results"/"top3_80_10_10.csv",index=False)

"""# 15. Extra Trees hyperparameter tuning

Extra Trees is tuned using RandomizedSearchCV. The search uses only the training data and five-fold cross-validation. The held-out test and validation sets are reserved for final evaluation.
"""

# 15. EXTRA TREES RANDOMIZED SEARCH
et=ExtraTreesRegressor(random_state=SEED,n_jobs=-1)
param_dist={
    "n_estimators":[200,400,600],
    "max_depth":[None,10,20,40],
    "min_samples_split":[2,5,10],
    "min_samples_leaf":[1,2,4],
    "max_features":[1.0,"sqrt"]
}
search=RandomizedSearchCV(
    estimator=et,
    param_distributions=param_dist,
    n_iter=20,
    scoring="r2",
    cv=5,
    random_state=SEED,
    n_jobs=-1,
    return_train_score=True
)
search.fit(X_train,y_train)

print("Best CV R²:",search.best_score_)
print("Best parameters:")
print(search.best_params_)

tuned_ET=search.best_estimator_
tuned_rows=[]
for split,XX,yy in [
    ("train",X_train,y_train),
    ("test",X_test,y_test),
    ("validation",X_val,y_val)
]:
    pred=tuned_ET.predict(XX)
    m=metric_dict(yy,pred)
    m.update({"Model":"Tuned Extra Trees","Split":split})
    tuned_rows.append(m)

tuned_eval=pd.DataFrame(tuned_rows)
display(tuned_eval)
tuned_eval.to_csv(ROOT/"results"/"tuned_extra_trees_metrics.csv",index=False)
joblib.dump(tuned_ET,ROOT/"models"/"tuned_extra_trees.joblib")

"""# 16. Model diagnostics

The tuned Extra Trees model is examined using predicted-versus-measured plots, residual plots, residual distributions, absolute-error distributions, and feature importance.
"""

# 16. DIAGNOSTICS
pred_test=tuned_ET.predict(X_test)
residual=y_test.to_numpy()-pred_test

plt.figure(figsize=(6,6))
plt.scatter(y_test,pred_test,s=10,alpha=.5)
lo=min(y_test.min(),pred_test.min()); hi=max(y_test.max(),pred_test.max())
plt.plot([lo,hi],[lo,hi],"k--")
plt.xlabel("Measured Ql"); plt.ylabel("Predicted Ql")
plt.title("Tuned Extra Trees — Predicted vs Actual")
plt.tight_layout(); plt.savefig(ROOT/"figures"/"tuned_ET_predicted_vs_actual.png",dpi=180); plt.show()

plt.figure(figsize=(7,4))
plt.scatter(pred_test,residual,s=10,alpha=.5)
plt.axhline(0,ls="--",color="black")
plt.xlabel("Predicted Ql"); plt.ylabel("Residual")
plt.title("Residuals vs Prediction")
plt.tight_layout(); plt.savefig(ROOT/"figures"/"residuals_vs_prediction.png",dpi=180); plt.show()

plt.figure(figsize=(7,4))
sns.histplot(residual,kde=True)
plt.xlabel("Residual"); plt.title("Residual Distribution")
plt.tight_layout(); plt.savefig(ROOT/"figures"/"residual_distribution.png",dpi=180); plt.show()

plt.figure(figsize=(7,4))
sns.histplot(np.abs(residual),kde=True)
plt.xlabel("Absolute Error"); plt.title("Absolute Error Distribution")
plt.tight_layout(); plt.savefig(ROOT/"figures"/"absolute_error_distribution.png",dpi=180); plt.show()

if hasattr(tuned_ET,"feature_importances_"):
    importance=pd.Series(
        tuned_ET.feature_importances_,index=FEATURES_A
    ).sort_values(ascending=False)
    display(importance.to_frame("importance"))
    importance.to_csv(ROOT/"results"/"feature_importance.csv")
    plt.figure(figsize=(8,5))
    importance.sort_values().plot(kind="barh")
    plt.title("Tuned Extra Trees Feature Importance")
    plt.tight_layout(); plt.savefig(ROOT/"figures"/"feature_importance.png",dpi=180); plt.show()

"""# 17. Field analysis

When the original field information is available, the analysis is performed for the complete dataset and separately for Fields A+C and Field B.

Field assignment follows the available Group information or the documented original row ordering.
"""

# 17. FIELD ANALYSIS
def assign_original_fields(frame):
    if DATA_MODE!="ORIGINAL_CS229":
        return None,"not applicable"

    if group_col in frame.columns:
        g=frame[group_col].astype(str).str.strip().str.upper()
        vals=set(g.dropna().unique())

        if {"A","B","C"}.issubset(vals):
            return g,"explicit Group labels"

    # Use original row position from the unfiltered source.
    if "_original_row" in frame.columns:
        pos=frame["_original_row"]

        label=pd.Series(
            index=frame.index,
            dtype="object"
        )

        label[pos.between(
            0,1488,
            inclusive="both"
        )]="A"

        label[pos.between(
            1489,3058,
            inclusive="both"
        )]="B"

        label[pos>=3059]="C"

        if label.notna().any():
            return label,"documented original row positions"

    return None,"insufficient evidence"


field_labels,evidence=assign_original_fields(clean)

if field_labels is None:
    print(
        "Field A+C vs B not run:",
        evidence
    )
else:
    print(
        "Field evidence:",
        evidence
    )

    for subset_name,mask in {
        "All fields":pd.Series(
            True,
            index=clean.index
        ),
        "A+C":field_labels.isin(["A","C"]),
        "B":field_labels.eq("B")
    }.items():

        sub=clean.loc[mask].copy()

        if len(sub)<20:
            print(
                "Skipping",
                subset_name,
                "— too few rows:",
                len(sub)
            )
            continue

        res,_,_,field_test_idx=run_screen(
            sub,
            FEATURES_A,
            TARGET_RAW
        )

        res.insert(
            0,
            "FieldSubset",
            subset_name
        )

        display(res)

        res.to_csv(
            ROOT/"results"/
            f"field_{norm(subset_name)}_80_20.csv",
            index=False
        )

"""# 18. Saving the results

The trained models, search results, metrics, figures, cleaned datasets, and run information are saved in the project directories for use in the report.
"""

# 18. SAVE EVERYTHING
for name,model in top3_models.items():
    joblib.dump(model,ROOT/"models"/f"top3_{norm(name)}.joblib")
joblib.dump(search,ROOT/"models"/"extra_trees_randomized_search.joblib")

manifest={
    "seed":SEED,
    "data_mode":DATA_MODE,
    "rows_loaded":int(len(raw)),
    "rows_after_3sigma":int(len(clean)),
    "target_raw":str(TARGET_RAW),
    "target_normalized":str(TARGET_NORM),
    "features_A":list(FEATURES_A),
    "features_B":list(FEATURES_B),
    "features_C":list(FEATURES_C),
    "top3_by_train_only_cv":top3,
    "extra_trees_best_params":search.best_params_,
    "field_evidence":evidence,
    "field_analysis_run":("field_labels" in globals() and field_labels is not None),
    "replacement_warning":(
        DATA_MODE=="PUBLIC_REPLACEMENT"
    )
}
(ROOT/"results"/"run_manifest.json").write_text(
    json.dumps(manifest,indent=2,default=str),
    encoding="utf-8"
)
print(json.dumps(manifest,indent=2,default=str))

"""# 19. Project outputs

The generated files include model-comparison tables, normalized-target results, Extra Trees tuning results, diagnostic plots, cleaned datasets, and field-level results when applicable.

# 20. Reproducibility

All experiments use the fixed random seed of 42. The notebook records the dataset, row counts, feature sets, selected models, and Extra Trees parameters so that the analysis can be reproduced.
"""